baseURL = 'https://dophucduy.github.io/Proposal_Strangers/'
defaultContentLanguage = 'en'
theme = 'hugo-theme-learn'
publishDir = 'docs'

[languages]
  [languages.en]
    languageCode = 'en-us'
    title = 'Flyora - Bird E-commerce Proposal'
    weight = 1
    languageName = 'English'
  [languages.vi]
    languageCode = 'vi-vn'
    title = 'Flyora - Đề xuất Thương mại Điện tử Chim Cảnh'
    weight = 2
    languageName = 'Tiếng Việt'

[params]
  themeVariant = "blue"
  disableSearch = false
  disableAssetsBusting = false
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = false
  disableInlineCopyToClipBoard = false
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.shortcuts]]
    name = "<i class='fab fa-github'></i> GitHub"
    identifier = "ds"
    url = "https://github.com/matcornic/hugo-theme-learn"
    weight = 10